import type { Metadata } from "next";
import "./globals.css";
import { ExampleFont} from "@/app/fonts";
import { QueryClientProvider } from "@/shared/apis/queryClientProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={ExampleFont.className}>
       <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
